// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQks8OdIHa_aunhFFHzaMeUvkk4EPNGNg',
    appId: '1:560958104264:web:268f573e51cd321a953bfd',
    messagingSenderId: '560958104264',
    projectId: 'doctor-appointmentapp-fa256',
    authDomain: 'doctor-appointmentapp-fa256.firebaseapp.com',
    storageBucket: 'doctor-appointmentapp-fa256.appspot.com',
    measurementId: 'G-LNPYZXCWG9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAn7CxJXDPB1pe_XJtwpkEqq5pVkpCW0H8',
    appId: '1:560958104264:android:06e612f950becdb9953bfd',
    messagingSenderId: '560958104264',
    projectId: 'doctor-appointmentapp-fa256',
    storageBucket: 'doctor-appointmentapp-fa256.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQKYLoHZu_p5I7xdrQELrB_WlfNPQW1Gk',
    appId: '1:560958104264:ios:fd732c6a2368963b953bfd',
    messagingSenderId: '560958104264',
    projectId: 'doctor-appointmentapp-fa256',
    storageBucket: 'doctor-appointmentapp-fa256.appspot.com',
    iosBundleId: 'com.example.drPatientAppointmentapp',
  );
}
